app.name=Library Dev
app.version=1.0.0-SNAPSHOT
logging.level=DEBUG
notification.enabled=false

# application-dev.properties
db.type=h2
db.url=jdbc:h2:mem:testdb
db.username=sa
db.password=


library.notification.smtp.host=smtp.gmail.com
library.notification.smtp.port=587
library.notification.smtp.username=alerts@library.com
library.notification.smtp.password=${SMTP_PASSWORD}
library.notification.smtp.enabled=true



